APP_PORT     = '9393'
APP_COOKIE   = '_ark'
APP_TITLE    = 'Ark'
APP_SUBTITLE = 'personal archive'
GITHUB_REPO  = 'https://github.com/louismachin/ark'
APP_ROOT     = File.expand_path('..', __dir__)
VIEWS_PATH   = File.join(APP_ROOT, 'views')
PUBLIC_PATH  = File.join(APP_ROOT, 'public')
DATA_PATH    = File.join(APP_ROOT, '..', 'data')
USERS_PATH   = File.join(APP_ROOT, '..', '.users')